layout_spectrum: 0.34575801715171794
typography_spectrum: 0.5975244276028236
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.3066094590134292
  lightness: 0.8556091659347351
  saturation: 0.4579694403529094
  rhythmicContrast: 0.4890480184385387
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Jennifer Flower
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: JenniferPhD.com
    url: 'http://JenniferPh.D.com'
    type: external
  - name: HowNOTtoGuides.com
    url: 'http://HowNOTtoGuides.com'
    type: external
favicon: null
title: Jennifer Flower's Blog
content: []
description: What I write when not writing other things
purpose:
  - type: external
    url: 'http://JenniferPhD.com'
    label: or try my business site
github: true
